### ISSUE TITLE
Load toplytics.js async and minify JS file

### ISSUE THREAD

**Issue by mariusveltan** [presslabs/toplytics#108]
In order to make the resource "toplytics/js/toplytics.js" non-render-blocking, I'd recommend loading the script async, in the footer area. This would allow the browser to continue with preparing the initial render of the page, loading the script in parallel.

Also, loading a minified version of the toplytics.js would be an idea to consider, maybe only loading the non-minified version when debugging the plugin.

**Comment by mariusveltan** [comment]
I use the following approach:

`<?php
/**
 * Make certain scripts load async, to make them non-render-blocking.
 *
 * @param string $tag The script tag for the enqueued script
 * @param string $handle The script's registered handle
 * @return string The updated script tag
 */
function hm_maybe_make_scripts_load_async( $tag, $handle ) {
    // Make Toplytics load async.
    if ( $handle == 'toplytics' ) {
        return str_replace( ' src', ' async src', $tag );
    }

    return $tag;
}

add_filter( 'script_loader_tag', 'hm_maybe_make_scripts_load_async', 10, 2 );`

**Comment by calind** [comment]
Moving into footer sounds good. For `async` loading I would rather wait for it to be standard WP behaviour. Will you try a pull request?
