### ISSUE TITLE
url_to_postid() doesn't work with custom post types

### ISSUE THREAD

**Issue by krodyrobi** [PressLabs/toplytics#114]
https://github.com/PressLabs/toplytics/blob/master/toplytics/toplytics.php#L436

http://betterwp.net/wordpress-tips/url_to_postid-for-custom-post-types/
http://sltaylor.co.uk/blog/get-post-id-from-custom-post-types-urls/

Request by: https://wordpress.org/support/topic/how-to-show-events-and-pages/

**Comment by Marius786** [comment]
This filter will handle this, see https://github.com/PressLabs/toplytics/blob/master/toplytics/toplytics.php#L438
