### ISSUE TITLE
Require/recommend template to be placed in theme instead of plugin folder

### ISSUE THREAD

**Issue by t-ionut** [presslabs/toplytics#118]

**Comment by krodyrobi** [comment]
The plugin checks for a template in the theme folder if that doesn't exist it loads the default one from the plugins folder.

**Comment by t-ionut** [comment]
I know that, I mean we need a visual notice recommending users NOT TO TWEAK THE DEFAULT TEMPLATE. If they update the plugin and lose the beautiful custom template, plugin maintainers will feel pain

**Comment by cristianuibar** [comment]
This has been addressed in V4. We now check the file and if it has been changed locally, it will display a warning on the overview page with instructions to copy it to custom.blade.php. Here is an example: https://cl.ly/b0b0e9dac5d7
