### ISSUE TITLE
css path is wrong

### ISSUE THREAD

**Issue by 1008k** [presslabs/toplytics#166]
Hello. Thanks for the great plugin!

The CSS path added when toplytics is installed is as follows.
`<link rel="stylesheet" id="toplytics/toplytics.php-css" href="https://exsample.com/wp-content/plugins/toplytics/components/../resources/backend/css/toplytics-admin.css?ver=4.0.10" media="all">`

The code below uses a relative path to register CSS, but isn't a relative path necessary?
[https://github.com/presslabs/toplytics/blob/de5947430a97dc1215744fa566b92e7b514a0fed/src/components/Backend.php#L211](https://github.com/presslabs/toplytics/blob/de5947430a97dc1215744fa566b92e7b514a0fed/src/components/Backend.php#L211)
[https://github.com/presslabs/toplytics/blob/de5947430a97dc1215744fa566b92e7b514a0fed/src/components/Backend.php#L227](https://github.com/presslabs/toplytics/blob/de5947430a97dc1215744fa566b92e7b514a0fed/src/components/Backend.php#L227)

I would appreciate it if you could consider it.

Best Regards.

**Comment by DenisFlorin** [comment]
Hello @1008k,

This is the path on my end: _/wp-content/plugins/toplytics/resources/backend/js/_

![2022-11-22_11-19](https://user-images.githubusercontent.com/38504865/203275334-599bd736-84b9-4e64-92b9-08586cffc82f.png)

![2022-11-22_11-20](https://user-images.githubusercontent.com/38504865/203275353-1b7d74d6-da5c-4e2c-b587-ed3a017ed49d.png)

Are you able to see a 404 error for these files when the plugin is installed on your website?

Thank you,

**Comment by 1008k** [comment]
@DenisFlorin Wow! The resources were loading just fine.
It's embarrassing that I made a rudimentary mistake😅

Thank you for confirming.
