### ISSUE TITLE
Show Postviews on Single Post Page

### ISSUE THREAD

**Issue by Marius786** [PressLabs/toplytics#61]

**Comment by zalmanu** [comment]
Out of this plugin's scope. A different plugin could do this.

**Comment by Marius786** [comment]
After a simple debate we figured out that the functionality 'to display postviews on each post' is out of the plugin's purpose. A proper way to solve your problem is to use the plugin 'Google Analytics Post Pageviews'. https://wordpress.org/plugins/google-analytics-post-pageviews/
