### ISSUE TITLE
Feature request/suggestion

### ISSUE THREAD

**Issue by jimihenrik** [PressLabs/toplytics#74]
Custom shortcode template would be nice.

*details: I'm using the plugin on a widget on the sidebar but as I wanted multiple time frames in tabs I use the shortcode on a text widget. To get the list's look like other content I changed the output of the shortcode to match. Like uls instead of ols and classes and such. I didn't see an option to do this without editing the plugin files. Maybe there was and I just didn't do my research.

Reference: http://www.suomikiekko.com/ ("Luetuimmat uutiset" -widget).

**Comment by Marius786** [comment]
Can you please add more details?

**Comment by Marius786** [comment]
This is covered by this commit a946da7e4f44d7f0430ebcdb0bdd1ad662d0f568 
 I mean you don't need to use a custom template anymore, just filter the shortcode output with `toplytics_shortcode_filter`.
