### ISSUE TITLE
Remove toplylics-template-realtime.php 

### ISSUE THREAD

**Issue by pdobrescu** [PressLabs/toplytics#80]
"Realtime" might be misleading as the same term is used within Google Analytics. By realtime we initially meant that the posts are being generated using JS and not PHP, avoiding in this way the page cache that most of the high traffic web sites have.

The proposal is therefore to change the name of the template into `toplytics-template-nocache.php`.

The plugin should still look for toplytics-template-realtime.php in the theme folder because existing customers might use this template and we need to keep it backwards compatible.

**Comment by Marius786** [comment]
The new approach for this problem is to remove the `toplytics-template-realtime.php` with the option from widget and to let the developers to use the JS or PHP code in `toplytics-template.php` file.
