### ISSUE TITLE
Add toplytics_post_type_filter

### ISSUE THREAD

**Issue by Marius786** [presslabs/toplytics#96]
We must add one filter at the line https://github.com/PressLabs/toplytics/blob/master/toplytics/toplytics.php#L430 in order to allow multiple post types to be processed by the plugin

**Comment by cristianuibar** [comment]
We have added this functionality via the Plugin Settings page in V4. Not sure if we still need a filter.

**Comment by cristianuibar** [comment]
Fixed in v4. Filter set via the settings page.
